### ISSUE TITLE
There needs to be stone for the dimension, other than just vanilla stone

### ISSUE THREAD

**Issue by Terenx** [Cryptic-Mushroom/CandyCraft#3]
Candy craft is supposed to be a dimension of candy, meaning that hard and inedible stone should have no place, I was thinking of maybe a kind of dark pink “Candy Rock” or “Sticky Stone”

**Comment by cipherzerox** [comment]
We're aware of this, and that's a great suggestion! But, in the future, if you could avoid opening issues like this, that would be appreciated, because it's not a bug, mainly a design matter. ^^

**Comment by Terenx** [comment]
Can you make a suggestion area then :)

**Comment by five0five** [comment]
the cryptic mushroom discord has a suggestions channel, its not exclusively bound to any mod, just specify which mod you're suggesting for, unless its clear already
