### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by ihaveacrushonjaidenanimations2068** [Cryptic-Mushroom/CandyCraft#4]
This mapping 'snapshot_20171003' was designed for MC 1.12! Use at your own peril.This mapping 'snapshot_20171003' was designed for MC 1.12! Use at your own peril.

#################################################
         ForgeGradle 2.3-SNAPSHOT-7764e3e        
  https://github.com/MinecraftForge/ForgeGradle  
#################################################
                 Powered by MCP                  
             http://modcoderpack.com             
     by: Searge, ProfMobius, R4wk, ZeuX          
     Fesh0r, IngisKahn, bspkrs, LexManos         
#################################################
:deobfCompileDummyTask
:getVersionJson
:extractUserdev
Download https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.4.2759/forge-1.12.2-14.23.4.2759.pom
Download https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.4.2759/forge-1.12.2-14.23.4.2759-userdev.jar
:downloadClient SKIPPED
:downloadServer SKIPPED
:splitServerJar SKIPPED
:mergeJars SKIPPED
:applyBinaryPatches
:deobfProvidedDummyTask
:extractDependencyATs SKIPPED
:extractMcpData SKIPPED
:extractMcpMappings SKIPPED
:genSrgs SKIPPED
:deobfMcMCP
Applying SpecialSource...
Applying Exceptor...
:sourceApiJava
:compileApiJava UP-TO-DATE
:processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE
:sourceMainJava
:compileJavaC:\Users\AJ\Desktop\cc\build\sources\main\java\com\crypticmushroom\candycraft\event\ServerEventCatcher.java:176: error: not a statement
                    ((EntityPlayer) event.getSource().getTrueSource().addStat(CCAchievements.killCookieCreeper));
                    ^
C:\Users\AJ\Desktop\cc\build\sources\main\java\com\crypticmushroom\candycraft\event\ServerEventCatcher.java:196: error: not a statement
                        (EntityPlayer) event.getSource().getTrueSource().addStat(CCAchievements.killQueenSlime);
                        ^
C:\Users\AJ\Desktop\cc\build\sources\main\java\com\crypticmushroom\candycraft\items\ItemCandyCrossbow.java:77: error: illegal start of expression
            worldIn.playSound(player, , 1.0F, 1.0F / (itemRand.nextFloat() * 0.4F + 1.6F) + f * 0.5F, SoundEvents.bpw);
                                      ^
C:\Users\AJ\Desktop\cc\build\sources\main\java\com\crypticmushroom\candycraft\misc\CCAchievements.java:48: error: illegal character: '\'
        craftSugarBlock = setAchievement("craftSugarBlock", 0, 0, new ItemStack(CCBlocks.sugarBlock), null, false);\
                                                                                                                   ^
4 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8 mins 41.528 secs

**Comment by ihaveacrushonjaidenanimations2068** [comment]
[gradle.log](https://github.com/Cryptic-Mushroom/CandyCraft/files/2899385/gradle.log)

**Comment by Andromander** [comment]
Should have hopefully been fixed as of https://github.com/Cryptic-Mushroom/CandyCraft/commit/82c83fa6a5c3eefdd5cd970980e991fc436e55f4. Can't say for a functional state.
